require 'pry'
require 'httparty'
require 'nokogiri'
require 'open-uri'

require_relative '../lib/address.rb'
require_relative '../lib/displayweather.rb'
require_relative '../lib/geolocation.rb'
# require_relative '../lib/scraper.rb'
require_relative '../lib/weather.rb'